### ISSUE TITLE
connecting to koa-graphql-rethinkdb 

### ISSUE THREAD

**Issue by nkostic** [joseluisq/vue-typescript-starter#1]
Hi @joseluisq ,

Can you suggest the proper way to integrate koa-graphql-rethinkdb repo (backend) with this fine vue-typescript-starter. I am new with this stack so any hint would be highly appreciated.  Thank You!

**Comment by joseluisq** [comment]
@nkostic sure, I will provide more detailed info about the integration between them.
Stay tuned!

**Comment by joseluisq** [comment]
Hey @nkostic ,
I have updated the README file at https://github.com/joseluisq/koa-graphql-rethinkdb (GraphQL server) Please follow the README steps.
Before, make sure that you have [Rethinkdb](https://github.com/rethinkdb/rethinkdb) installed.

Then when you GraphQL server is running you can run this `vue-typescript-starter`.
In `vue-typescript-starter` you don't need to change anything "at first" (but if you want you can customize it later)

**Comment by nkostic** [comment]
@joseluisq thanks for a quick response,

OK I followed the instructions and both projects successfully completed build (yarn build than yarn start), my rethinkDb docker container is running and I can access to http://localhost:4020/graphiql and fiddle around with graphql no problem.

Now in separate folder - vue-typescript-starter (outside koa-graphql-rethinkdb ) I run yarn build, than yarn start and  I get message successfully done in like 1.61 sec.

How do I access now to vue-typescript-starter through browser URL ?

Maybe better question is where should I locate vue-typescript-starter folder, inside koa-graphql-rethinkdb ?

Thank you!

**Comment by joseluisq** [comment]
> How do I access now to vue-typescript-starter through browser URL ?

That runs on :4044 port, you can see on your terminal (http://localhost:4044)

> Maybe better question is where should I locate vue-typescript-starter folder, inside koa-graphql-rethinkdb ?

Now these are separated. But If you want you can put them together (read the Koa docs for that, maybe you can put your `vue-typescript-starter` built files into one directory and use a Koa route to expose it on the same server), or simply run another docker container with your static `vue-typescript-starter` generated. Remember at the end `vue-typescript-starter` is a static site that you can put it any place that you want.

**Comment by joseluisq** [comment]
In addition, if you put your `vue-typescript-starter` on another server,  you can change the URL of your GraphQL Server API at [vue-typescript-starter/src/index.ts](https://github.com/joseluisq/vue-typescript-starter/blob/master/src/index.ts#L11).

**Comment by nkostic** [comment]
> That runs on :4044 port, you can see on your terminal (http://localhost:4044)

OK so this part is confusing me when I run yarn start on vue-typescript-starter my console output just says it's finished, I do not get any other information. See bellow:

![terminal](https://user-images.githubusercontent.com/426266/32943722-4be674e6-cb4a-11e7-8dc0-4b3ff2ae3409.jpg)

So there is no localhost:4044 

Should I mentioned I am working currently on Windows ?

**Comment by joseluisq** [comment]
Sorry, `yarn build` command builds your app only into static files at `./dist`
It doesn't run any server.

**Comment by nkostic** [comment]
I understand, but my next command is yarn start and it seems that is doing the same but for different env. OK I was expecting that yarn start will run the server ...

**Comment by joseluisq** [comment]
Feel free to adapt it your requirements 👍

**Comment by nkostic** [comment]
Thank You @joseluisq!

**Comment by joseluisq** [comment]
Your welcome!

**Comment by nkostic** [comment]
The problem I was having is specific to Windows, had to update package.json.
`SET NODE_ENV=development`  in particular vs `NODE_ENV=development`
and I had to add & to concatenate commands : / 
Thanks for the help.

**Comment by joseluisq** [comment]
> The problem I was having is specific to Windows, had to update package.json.
> SET NODE_ENV=development in particular vs NODE_ENV=development
> and I had to add & to concatenate commands : /
> Thanks for the help.

Cool!
because my workstation was Linux OS when I published this repo xD
So, for full cross-environment variables I recommend to use https://github.com/kentcdodds/cross-env

Update your package.json to:

```
cross-env NODE_ENV=development
```

👍
